name: ali_fronted
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0  
  intl: ^0.18.1  # <---- AGREGADO PARA EL PIE CHART ANIMADO

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustration_home.png
    - assets/fondo_home.png
    - assets/nino_home.png

  fonts:
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
