name: ali_fronted
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Habilita mensajes y formatos localizados (es, en, etc.)
  flutter_localizations:
    sdk: flutter

  http: ^0.13.5
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  intl: ^0.20.2          # Manejo de fechas/horas localizadas
  timeago: ^3.6.0        # Fechas relativas (“hace 2 días”, etc.)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustration_home.png
    - assets/fondo_home.png
    - assets/nino_home.png

  fonts:
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
